### ISSUE TITLE
what is the performance

### ISSUE THREAD

**Issue by Jasperty** [Tudor67/Sentence-Selection-For-Question-Answering#3]

**Comment by Tudor67** [comment]
Hi!
After some experiments on [SQuAD1.1 dataset](https://rajpurkar.github.io/SQuAD-explorer/) I got the following results:
![image](https://user-images.githubusercontent.com/12481060/52535514-1093bb80-2d58-11e9-9f7e-6a3af4425780.png)

Do not forget that SQuAD1.1 is a reading comprehension dataset and I try to find the sentence that contains the answer to a given question. The paragraphs with candidate answers are very small (~10 sentences):

![image](https://user-images.githubusercontent.com/12481060/52535741-ae888580-2d5a-11e9-8932-39daa4fce48f.png)

For more details, take a look at the project journal and presentation: https://github.com/Tudor67/Sentence-Selection-For-Question-Answering/tree/master/docs

Notation:
`Prec@1`: precision at 1;
`MAP`: mean average precision;

`LR`: logistic regression;
`BM25`: [Okapi BM25 (ranking function)](https://en.wikipedia.org/wiki/Okapi_BM25)

**Comment by Jasperty** [comment]
what is the recall?

**Comment by Tudor67** [comment]
I didn't compute the recall. 

I think that `P@k` and `MAP` are enough to get a intuition of how good your methods/solutions are.

__In the case of `SQuAD1.1`__ each query has just one relevant sentence (with the correct answer). As a result, there should be a strong correlation between `P@1` and `R@1`. It is possible that `P@1` == `R@1` (just in this particular case), but I am not sure :) .

Notation:
`P@1`: precision at 1;
`R@1`: recall at 1.
